Models/Investor/Book.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Investor.Models.Investor
{
    public class Book
    {
        [Key]
        public int Id { get; set; }
    //    [Required]
      //  string bookFile { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string description { get; set; }
        [Required]
        public string type { get; set; }
        [Required]
        public string author { get; set; }
        [Required(ErrorMessage = "Please enter the book price")]
        [Range(0, double.MaxValue, ErrorMessage = "Price must be a non-negative value")]
        public double price { get; set; }

        public string image { get; set; }

        [ForeignKey("InvestoreAccounts")]
        public int InvestoreAccountId { get; set; }

        [ForeignKey("Coupon")]
        public int ? CouponId { get; set; }
        public Coupon ? Coupon { get; set; }

    }
}

Models/Investor/Coupon.cs
using System.ComponentModel.DataAnnotations;

namespace Investor.Models.Investor
{
    public class Coupon
    {
        [Key]
        public int id { get; set; }
        [Required]
        public string code { get; set; }
        
        [Required(ErrorMessage = "Please enter the value of discount")]
        [Range(0.01,1, ErrorMessage = "discount range between {1} and {2}")]
        public double discount { get; set; }
        [Required]
        public string timePeriodc { get; set; }

       public ICollection<Book> book { get; set; }
    }
}

Models/Investor/InvestoreAccount.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Investor.Models.Investor
{
    public class InvestoreAccount
    {
        [Key]
        public int id { set; get; }
        [Required]
        public string userName { set; get; }
        [Required]
        public string password { set; get; }
        [Required]
        public string companyName { set; get; }

        [ForeignKey("person")]
        public int PersonId { set; get; }
        public  Person person { set; get; }
        public ICollection<Profit> profit { set; get; }
        public ICollection<Book> book { set; get; }
    }
}

Models/Investor/Profit.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Investor.Models.Investor
{
    public class Profit
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public double profit { get; set; }
        [Required]
        public DateTime date { get; set; }

        [ForeignKey("investoreAccount")]
        public int investoreAccountId { get; set; }
        public InvestoreAccount investoreAccount { get; set; }
    }
}

Controllers/InvestorController.cs
using Investor.Data;
using Investor.Models;
using Investor.Models.Investor;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Net;
using static Azure.Core.HttpHeader;
using static System.Reflection.Metadata.BlobBuilder;

namespace Investor.Controllers
{
    public class InvestorController : Controller
    {

        public InvestorController(AppDbContext db) {
            _db = db;
        
        }

        private readonly AppDbContext _db;

        //Get
        public IActionResult Details()
        {
            // IEnumerable<Book> bookData = _db.book.ToList();
            createSelecteBook();
            return View();
        }
        void createSelecteBook(int selecteId = 1) {

            List<Book> books = _db.book.Where(q => q.CouponId == null).ToList();
           // SelectList listBook = new SelectList(books, "Id", "name",selecteId);
            ViewBag.bookList = books;

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(DetailsModel detailsModel)
        {
           

            if (ModelState.IsValid)
            {
                Coupon coupon = new Coupon
                {
                    code = detailsModel.code,
                    discount = detailsModel.discount,
                    timePeriodc = detailsModel.timePeriodc,
                };
                _db.coupon.Add(coupon);
                _db.SaveChanges();
               
                UpdateBooksCouponId(coupon.id, detailsModel.bookId);

                return RedirectToAction("ViewItems");
            }
            else
            {
                return View();
            }
        }

        private void UpdateBooksCouponId(int couponId, int bookId)
        {
            Book book = _db.book.FirstOrDefault(b => b.Id == bookId);
            

            if (book != null)
            {
                book.CouponId = couponId;
                _db.Update(book);
                _db.SaveChanges();
            }


            }

        public IActionResult ViewItems()
        {
            List<Book> booksItem = _db.book.Where(q => q.InvestoreAccountId == 1).Include(c => c.Coupon).ToList();

            return View(booksItem);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteBook(int bookId)
        {

            Book bookToDelete = _db.book.FirstOrDefault(q => q.Id == bookId);

            if (bookToDelete != null)
            {
                _db.book.Remove(bookToDelete);
                _db.SaveChanges();
            }

            return RedirectToAction("ViewItems");
        }

        // Get
        public IActionResult AddItem()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddItem(Book book)
        {
            if (ModelState.IsValid)
            {
                _db.book.Add(book);
                _db.SaveChanges();
                return RedirectToAction("ViewItems");
            }
            else
            {
                return View(book);
            }
        }

        public IActionResult Setting()
        {
            return View();
        }

        public IActionResult ViewCoupon()
        {
           List<Coupon> coupon= _db.coupon.Include(c => c.book).ToList();
            return View(coupon);
        }

        // get
        public IActionResult EditCoupon(int ? id)
        {
            if (id == null || id == 0) { 
            
            return NotFound();
            
            }
            var item = _db.coupon.Find(id);
            if(item == null)
            {
                return NotFound();
            }
            return View(item);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCoupon(Coupon coupon)
        {
            if (ModelState.IsValid)
            {

                _db.coupon.Update(coupon);
                _db.SaveChanges();

                return RedirectToAction("ViewItems");
            }
            else {
                return View();
            }

          
        }



        public IActionResult DeleteCoupon(int id)
        {
            Coupon coupon = _db.coupon.Include(c => c.book).FirstOrDefault(q => q.id == id);

            if (coupon != null)
            {
                // Delete associated books first
               // foreach (var book in coupon.book.ToList())
                //{
                  //  _db.book.Remove(book);
                //}

                _db.coupon.Remove(coupon);
                _db.SaveChanges();
            }

            return RedirectToAction("ViewItems");
        }

       
        // get 
        public IActionResult EditItem(int? id)
        {
            if (id == null || id == 0)
            {

                return NotFound();

            }
            var item = _db.book.Find(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditItem(Book book)
        {
            if (ModelState.IsValid)
            {

                _db.book.Update(book);
                _db.SaveChanges();

                return RedirectToAction("ViewItems");
            }
            else
            {
                return View();
            }


        }





    }
}

Views/Investor/AddItem.cshtml
@using Investor.Models.Investor
@model Book
@{
    List<String> bookType = ["Historical", "novel", "scientific", "Human Development", "geology","detective story"];
    
    
    
    

}

<style>
    .container {
        border: 2px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        text-align: center;
        max-width: 500px;
        margin: 30px auto; /* Add this line to center the container horizontally */
    }

    .upload-icon {
        font-size: 30px;
        color: #999;
        margin-bottom: 10px;
    }

    .upload-input {
        display: none;
    }

    .upload-label {
        cursor: pointer;
        background-color: lightskyblue;
        color: #fff;
        padding: 10px 10px;
        border-radius: 5px;
    }

    .form-group {
        width: 100%;
        max-width: 600px; /* Adjust the max-width to your preference */
        margin: 0 auto; /* Add this line to center the form horizontally */
    }

    .center-button {
        display: flex;
        justify-content: center; /* Add this line to center the button horizontally */
        align-items: center; /* Add this line to center the button vertically */
       margin:20px;
    }

    button {
        width: 600px;
        margin: 0;
    }
</style>
<form method="post">


   
        <div class="container">
        <span asp-validation-for="image" class="text-danger"></span>
        <br>
            <i class="upload-icon fas fa-plus"></i>
            <input asp-for="image" type="file" class="upload-input"  />
            <label asp-for="image" class="upload-label">Choose image <i class="bi bi-file-image"></i></label>
        </div>
   
        <div class="form-group">
        
           <label asp-for="name" class="form-label mt-4">Name</label>
        <br>
        <span asp-validation-for="name" class="text-danger"></span>
            <input asp-for="name" type="text" class="form-control" aria-describedby="emailHelp" placeholder="Book name">
        </div>

        <div class="form-group">
        
       
        <label asp-for="price" class="form-label mt-4">Price</label>
        <br>
        <span asp-validation-for="price" class="text-danger"></span>
            <input asp-for="price" type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Price">
        </div>

        <div class="form-group">
       
      
        <label asp-for="author" class="form-label mt-4">Author</label>
        <br>
        <span asp-validation-for="author" class="text-danger"></span>
            <input asp-for="author" type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Author name">
        </div>

        <div class="form-group">
        
        
            <label asp-for="description" class="form-label mt-4">Book description</label>
        <br>
        <span asp-validation-for="description" class="text-danger"></span>
            <textarea asp-for="description" class="form-control"  rows="2"></textarea>
        </div>

        <div class="form-group">
        
        
        <label asp-for="type" class="form-label mt-4">Book type</label>
        <br>
        <span asp-validation-for="type" class="text-danger"></span>
      
            <select asp-for="type" class="form-select">
                 
            @{
                foreach (var tay in bookType)
                {
                    <option>@tay</option>

                }
            }
            </select>
        </div>

        <input type="hidden" asp-for="InvestoreAccountId" value="1"></input>
    <input type="hidden" asp-for="CouponId" value="" />
    <input type="hidden" asp-for="Coupon" value="" />
    
         
    
        <div class="center-button">
            <button class="btn btn-lg btn-primary" type="submit">Block button</button>
        </div>
   

</form>

Views/Investor/Details.cshtml
@using Investor.Models.Investor
@using System.Collections
@using System.Net

@model DetailsModel

@{
    String title = "Add coupon to multiple books";
    List<string> time = new List<string> { "For24", "ForMonth", "For3Month" };
    int inde = 0;
}

<style>
  

    .content-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        background-color: #ffffff;
        padding: 20px;
    }

    .image-container {
        display: flex;
        align-items: center;
        justify-content: center;
        margin-bottom: 10px;
        margin-top: 30px;
    }

        .image-container img {
            width: 150px;
            height: 150px;
            object-fit: cover;
            border-radius: 50%;
        }

    .form-group {
        margin-bottom: 10px;
    }

    .narrow-input {
        width: 500px;
    }

    .button-container {
        display: flex;
        justify-content: flex-end;
    }
</style>

<div class="content-container">
    <div class="image-container">
        <h2 style="text-align: left; padding-left: 10px;">Welcome Gaith</h2>
    </div>

    <form method="post">
        <h3 class="text-primary">@title</h3>

        <div class="form-group">
            <label asp-for="code" class="form-label mt-4">Coupon code</label>
            <br />
            <span asp-validation-for="code" class="text-danger"></span>
            <input asp-for="code" class="form-control narrow-input" aria-describedby="emailHelp" placeholder="Coupon code" />
        </div>

        <div class="form-group">
            <label asp-for="discount" class="form-label mt-4">Discount</label>
            <br />
            <span asp-validation-for="discount" class="text-danger"></span>
            <input asp-for="discount" class="form-control narrow-input" placeholder="Discount" autocomplete="off" />
        </div>

        <div class="form-group">
            <label for="exampleSelect2" class="form-label mt-4">Choose books supporting the coupon</label>
            <select class="form-select" id="exampleSelect2" asp-for="bookId">
                @foreach (Book book in ViewBag.bookList)
                {
                    <option value="@book.Id">@book.name</option>
                }
            </select>
        </div>

        <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
            @foreach (var val in time)
            {
                <input asp-for="timePeriodc" type="radio" class="btn-check" id="btnradio@(inde+1)" autocomplete="off" value="@val" />
                <label class="btn btn-outline-primary" for="btnradio@(inde+1)">@val</label>
                inde++;
            }
        </div>
        <br />
        <span asp-validation-for="timePeriodc" class="text-danger"></span>
        <div class="button-container">
            <button type="submit" class="btn btn-primary">OK</button>
        </div>
    </form>
</div>

Views/Investor/EditCoupon.cshtml
@using Investor.Models.Investor
@model Coupon


<style>
    /* Center the form and heading */
    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
        text-align: center;
    }

    /* Style the form */
    .coupon-form {
        width: 500px; /* Increase the width */
        height: 400px; /* Increase the height */
        padding: 20px;
        background-color: #f2f2f2;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }

    /* Style the form */
  

    /* Style the form labels */
    .control-label {
        font-weight: bold;
        color: #333;
    }

    /* Style the input fields */
    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-bottom: 10px;
    }

    /* Style the validation error messages */
    .text-danger {
        color: red;
    }

    /* Style the submit button */
    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        border-radius: 4px;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }

    /* Style the back link */
    .back-link {
        display: inline-block;
        margin-top: 20px;
        color: #007bff;
        text-decoration: none;
    }
</style>

<div class="container">
    <h4>Coupon</h4>
    <br/>
    <br />
    <div class="coupon-form">
        <form method="post" asp-action="EditCoupon">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="code" class="control-label"></label>
                <input asp-for="code" class="form-control" />
                <span asp-validation-for="code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="discount" class="control-label"></label>
                <input asp-for="discount" class="form-control" />
                <span asp-validation-for="discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="timePeriodc" class="control-label"></label>
                <input asp-for="timePeriodc" class="form-control" />
                <span asp-validation-for="timePeriodc" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="book" value= "" class="form-control" />
            
           
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <a asp-action="ViewCoupon" class="back-link">Back to List</a>
</div>

Views/Investor/EditItem.cshtml
@using Investor.Models.Investor
@model Book




<style>

    /* Reset default browser styles */
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }

    /* Container for the form */
    .row {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    /* Form styles */
    form {
        width: 400px;
        padding: 40px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 20px;
    }

    label {
        font-weight: bold;
        color: #333;
    }

    input[type="text"],
    input[type="number"] {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        background-color: #f7f7f7;
        font-size: 14px;
        color: #333;
        transition: border-color 0.3s ease;
    }

        input[type="text"]:focus,
        input[type="number"]:focus {
            outline: none;
            border-color: #007bff;
        }

    input[type="submit"] {
        width: 100%;
        padding: 12px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }

    a {
        display: block;
        margin-top: 10px;
        color: #007bff;
        text-decoration: none;
        font-size: 14px;
        transition: color 0.3s ease;
    }

        a:hover {
            color: #0056b3;
        }

</style>



<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditItem">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="type" class="control-label"></label>
                <input asp-for="type" class="form-control" />
                <span asp-validation-for="type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="author" class="control-label"></label>
                <input asp-for="author" class="form-control" />
                <span asp-validation-for="author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="image" class="control-label"></label>
                <input asp-for="image" class="form-control" />
                <span asp-validation-for="image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="InvestoreAccountId" class="form-control" type="hidden" />
                <span asp-validation-for="InvestoreAccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="CouponId" class="form-control" type="hidden" />
                <span asp-validation-for="CouponId" class="text-danger"></span>
              
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Investor/Setting.cshtml
@{
}

<style>
    body{
        background-color: lightgray;
    }

    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
        max-width: 800px;
        margin: 0 auto;
        margin-top: 50px;
        position: relative;
        background-color: rgba(255, 255, 255, 0.9); /* Add a background color to make the text visible */
        border-radius: 10px;
        padding: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);
    }

    .image {
        margin: 20px 0;
        height: 200px;
        width: 600px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);
    }

    h1 {
        font-size: 32px;
        margin-bottom: 10px;
        color: #4285f4;
    }

    h5 {
        font-size: 18px;
        margin-bottom: 5px;
    }

    .button-container {
        display: flex;
        justify-content: center;
        margin-top: 30px;
    }

        .button-container button {
            margin: 0 10px;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

            .button-container button:hover {
                background-color: #4285f4;
                color: #fff;
            }

    .btn-primary {
        background-color: #4285f4;
        border-color: #4285f4;
    }

    .btn-danger {
        background-color: #dc3545;
        border-color: #dc3545;
    }

    .btn-primary,
    .btn-danger {
        color: #fff;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    th,
    td {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    th {
        background-color: #f2f2f2;
    }
</style>

<div class="container">
    

    <div class="container">
        <table>
            <tr>
                <th>user</th>
                <th>information</th>
            </tr>

            <tr>
                <td>company name</td>
                <td>Alaraby</td>
            </tr>

            <tr>
                <td>Name</td>
                <td>Gaith Kozali</td>
            </tr>
            <tr>
                <td>Address</td>
                <td>Damascus</td>
            </tr>
            <tr>
                <td>Book count</td>
                <td>100</td>
            </tr>
            <tr>
                <td>Profit last month</td>
                <td>$200</td>
            </tr>
        </table>
    </div>

    <br />
    <div class="button-container">
       
        <button type="button" class="btn btn-success"> Profits graph</button>
        <button type="button" class="btn btn-danger">Log Out</button>
    </div>
</div>

Views/Investor/ViewCoupon.cshtml
<style>
    .coupon-container {
        padding: 10px 20px; /* Add padding from right and left */
        margin-bottom: 20px;
        background-color: #f5f5f5;
        border: 1px solid #ddd;
        border-radius: 4px;
    }

    .coupon-details {
        padding-left: 20px;
    }

    .coupon-title {
        font-size: 20px;
        font-weight: bold;
        margin-bottom: 10px;
    }

    .coupon-info {
        margin-bottom: 10px;
    }

    .coupon-books {
        margin-top: 10px;
    }

    .book-info {
        margin-bottom: 5px;
    }

    .edit-link,
    .delete-link {
        color: #007bff;
        text-decoration: none;
        margin-right: 10px;
    }

        .edit-link:hover,
        .delete-link:hover {
            text-decoration: underline;
        }
</style>

<h4>Coupon</h4>

@foreach (var coupon in Model)
{
    <div class="coupon-container">
        <div class="coupon-details">
            <div class="coupon-title">Coupon Information</div>
            <div class="coupon-info">
                <span class="font-weight-bold">Code:</span> @coupon.code
            </div>
            <div class="coupon-info">
                <span class="font-weight-bold">Discount:</span> @coupon.discount
            </div>
            <div class="coupon-info">
                <span class="font-weight-bold">Time Period:</span> @coupon.timePeriodc
            </div>
            <div class="coupon-books">
                <div class="coupon-title">Books</div>
                @foreach (var book in coupon.book)
                {
                    <div class="book-info">
                        <span class="font-weight-bold">ID:</span> @book.Id
                    </div>
                    <div class="book-info">
                        <span class="font-weight-bold">Name:</span> @book.name
                    </div>
                    <div class="book-info">
                        <span class="font-weight-bold">Price:</span> @book.price
                    </div>
                    <br />
                }
            </div>
        </div>
        <div>
            <a asp-controller="Investor" asp-action="EditCoupon" asp-route-id="@coupon.id" class="edit-link">Edit</a> |
            <a asp-controller="Investor" asp-action="DeleteCoupon" asp-route-id="@coupon.id" class="delete-link">Delete</a>
        </div>
    </div>
    <hr />
}

Views/Investor/ViewItems.cshtml
@using Investor.Models.Investor
@model List<Book>

<!DOCTYPE html>
<html>
<head>
    <title>Book Details</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
    <style>
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ddd;
            display: flex;
            align-items: flex-start;
            justify-content: space-between;
            position: relative;
        }

        .book-image {
            width: 200px;
            height: 200px;
            object-fit: cover;
            margin-right: 20px;
            border-radius: 50%; /* Added circular border */
            border: 2px solid #ddd; /* Added border */
        }

        .book-info {
            flex-grow: 1;
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        .book-name {
            font-size: 24px;
            margin-bottom: 10px;
        }

        .book-description {
            font-size: 16px;
            margin-bottom: 10px;
        }

        .coupon-id,
        .book-price {
            font-size: 14px;
            margin-bottom: 5px;
        }

        .row {
            display: flex;
            gap: 20px;
        }

        .buttons-container {
            position: absolute;
            bottom: 10px;
            right: 10px;
            display: flex;
            gap: 10px;
        }

        .delete-button,
        .edit-button {
            padding: 5px 10px;
            background-color: #f44336;
            color: #fff;
            border: none;
            cursor: pointer;
            border-radius: 5px; /* Added border radius */
        }

        .edit-button {
            background-color: #2196f3;
        }
    </style>
</head>
<body>
    <div class="row">
        @foreach (Book item in Model)
        {
            <div class="container">
                <img class="book-image" src="~/images/company.jpg" alt="Book Image">
                <div class="book-info">
                    <h2 class="book-name">Book Name: @item.name</h2>
                    <p class="book-description">Book Description: @item.description</p>
                    <p class="coupon-id">Coupon code: @(item.CouponId != null ? item.Coupon.code : "No coupon available")</p>
                    <p class="book-price">Price: @item.price</p>
                </div>
                <div class="buttons-container">
                    <form method="post" asp-action="DeleteBook" asp-controller="Investor">
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="bookId" value="@item.Id" />
                        <button class="delete-button" type="submit">Delete</button>
                    </form>
                    <a class="edit-button" asp-controller="Investor" asp-action="EditItem" asp-route-id="@item.Id">Edit</a>
                </div>
            </div>
        }
    </div>
</body>
</html>